### PR TITLE
Updating commands to Symfony2 RC1

### PR DESCRIPTION
**Pull request by johnwards**

### CODE REVIEW

**Comment by johnwards** [comment]
@pablodip could you create an rc1 branch for this so I can update the project we are working on @whiteoctober please?

I've updated that project to RC1 symfony, and want to merge it back into develop

**Comment by pablodip** [comment]
Done!

**Comment by johnwards** [comment]
@pablodip can we get this merged into master now we are on RC3?

**Comment by pablodip** [comment]
Done.

**Pull request closed without merging**
